"""
ubice.sbom.spdx
~~~~~~~~~~~~~~~
Generates a minimal SPDX 2.3 JSON SBOM from a list of ComponentMatch results.

Corresponds to UBICE Module 5 (SBOM Generation) in the GSoC proposal.
Full implementation will produce SPDX 3.0 + CycloneDX 1.6 with Sigstore signing.

Usage::

    doc = SPDXDocument(name="my-firmware", version="1.0")
    doc.add_component(match, fv)
    print(doc.to_json())
"""
from __future__ import annotations

import datetime
import hashlib
import json
import uuid
from typing import Optional

from ubice.extractor.elf import FeatureVector
from ubice.fingerprint.csd import ComponentMatch

__all__ = ["SPDXDocument"]

_SPDX_VERSION = "SPDX-2.3"
_DATA_LICENSE = "CC0-1.0"
_TOOL_NAME = "UBICE-PoC-0.1.0"


class SPDXDocument:
    """
    Builds a minimal SPDX 2.3 JSON document.

    In the full UBICE implementation this will:
      - Emit SPDX 3.0 with SBOM relationship types
      - Generate CycloneDX 1.6 alongside
      - Sign with Sigstore (Fulcio + Rekor)
    """

    def __init__(self, name: str, version: str = "NOASSERTION") -> None:
        self._doc_id = "SPDXRef-DOCUMENT"
        self._name = name
        self._version = version
        self._packages: list[dict] = []
        self._relationships: list[dict] = []
        self._created = datetime.datetime.utcnow().isoformat() + "Z"
        self._doc_namespace = (
            f"https://ubice.fossology.org/sbom/{uuid.uuid4()}"
        )

    def add_component(
        self,
        match: ComponentMatch,
        fv: Optional[FeatureVector] = None,
    ) -> str:
        """
        Add a detected component to the SBOM.
        Returns the SPDX element ID for use in relationships.
        """
        spdx_id = f"SPDXRef-{match.package_name.replace('/', '-')}-{len(self._packages)}"
        pkg: dict = {
            "SPDXID": spdx_id,
            "name": match.package_name,
            "versionInfo": match.version,
            "downloadLocation": "NOASSERTION",
            "filesAnalyzed": False,
            "licenseConcluded": match.license_spdx or "NOASSERTION",
            "licenseDeclared": match.license_spdx or "NOASSERTION",
            "copyrightText": "NOASSERTION",
            "externalRefs": [
                {
                    "referenceCategory": "PACKAGE-MANAGER",
                    "referenceType": "purl",
                    "referenceLocator": match.purl,
                }
            ],
            "comment": (
                f"Detected by UBICE Stage {match.match_stage} fingerprinting. "
                f"Confidence: {match.confidence_pct}%."
                + (f" TLSH distance: {match.tlsh_distance}." if match.tlsh_distance else "")
            ),
        }
        if fv and fv.sha256:
            pkg["checksums"] = [
                {"algorithm": "SHA256", "checksumValue": fv.sha256}
            ]
        self._packages.append(pkg)
        self._relationships.append({
            "spdxElementId": self._doc_id,
            "relationshipType": "DESCRIBES",
            "relatedSpdxElement": spdx_id,
        })
        return spdx_id

    def to_dict(self) -> dict:
        return {
            "spdxVersion": _SPDX_VERSION,
            "dataLicense": _DATA_LICENSE,
            "SPDXID": self._doc_id,
            "name": self._name,
            "documentNamespace": self._doc_namespace,
            "creationInfo": {
                "created": self._created,
                "creators": [f"Tool: {_TOOL_NAME}", "Organization: FOSSology"],
                "comment": "Generated by UBICE proof-of-concept. Not for production use.",
            },
            "packages": self._packages,
            "relationships": self._relationships,
        }

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)
